CREATE TYPE project_type AS ENUM ('BUILD', 'PURCHASE');

CREATE TYPE project_status AS ENUM ('PLANNING', 'ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELED');

CREATE TYPE project_role AS ENUM ('OWNER', 'ADMIN', 'MEMBER', 'VIEWER');
