CREATE TABLE project
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id       UUID           NOT NULL DEFAULT gen_random_uuid(),
    name              VARCHAR(255)   NOT NULL,
    description       TEXT,
    type              project_type   NOT NULL,
    start_date        DATE           NOT NULL,
    expected_end_date DATE,
    end_date          DATE,
    status            project_status NOT NULL DEFAULT 'PLANNING',
    created_by        BIGINT         NOT NULL,
    created_at        TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ,

    CONSTRAINT uk_project_external_id UNIQUE (external_id),
    CONSTRAINT uk_project_name UNIQUE (name),

    CONSTRAINT fk_project_user FOREIGN KEY (created_by)
        REFERENCES app_user (id)
        ON DELETE CASCADE,

    CONSTRAINT chk_expected_end_date CHECK (expected_end_date >= start_date),
    CONSTRAINT chk_end_date CHECK (end_date >= start_date)
);

CREATE INDEX idx_project_status ON project (status);
CREATE INDEX idx_project_type ON project (type);