CREATE TABLE project_status_history
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id UUID           NOT NULL DEFAULT gen_random_uuid(),
    project_id  BIGINT         NOT NULL,
    status      project_status NOT NULL,
    created_at  TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ,

    CONSTRAINT uk_project_status_history_external_id UNIQUE (external_id),

    CONSTRAINT fk_project_status_history_project FOREIGN KEY (project_id)
        REFERENCES project (id) ON DELETE CASCADE
);

CREATE INDEX idx_project_status_history_project_id ON project_status_history (project_id);